"""
HSE Prompt Generator with automatic alert summarization
for Warehouse Safety Monitoring LLM
"""

import json
from collections import defaultdict
from datetime import datetime
from statistics import mean

from jinja2 import Template


SAFETY_RULES = {
    "Person No Hardhat": {
        "meaning": "فرد بدون کلاه ایمنی",
        "risk": "خطر آسیب سر در اثر سقوط اجسام",
        "action": "الزام استفاده از کلاه ایمنی"
    },

    "Person No Vest": {
        "meaning": "فرد بدون جلیقه ایمنی",
        "risk": "کاهش دیده شدن فرد توسط ماشین‌آلات",
        "action": "استفاده از جلیقه شبرنگ"
    },

    "Person No PPE": {
        "meaning": "عدم استفاده از تجهیزات حفاظت فردی",
        "risk": "افزایش احتمال آسیب کاری",
        "action": "بررسی و الزام PPE"
    },

    "NO-Mask": {
        "meaning": "عدم استفاده از ماسک",
        "risk": "تماس با گرد و غبار یا مواد خطرناک",
        "action": "استفاده از ماسک استاندارد"
    }
}


class AlertsSummarizer:
    """
    Summarize object detection alerts for Large Language Model (LLM) prompts.

    This class processes raw alert data generated by the warehouse safety
    monitoring system and produces aggregated statistics that can be used
    to generate concise or detailed prompts for an LLM.

    During initialization, alerts are grouped by object track and object
    class to compute summary statistics such as incident counts and object
    speeds.

    Attributes
    ----------
    alerts : list[dict]
        List of raw alert dictionaries extracted from the input data.

    total_alerts : int
        Total number of alerts contained in the dataset.

    summary_by_track : dict
        Aggregated statistics grouped by tracking identifier.

    summary_by_class : dict
        Aggregated statistics grouped by detected object class.

    Notes
    -----
    This class assumes that every alert dictionary contains at least the
    following keys:

    - ``track_id``
    - ``class_name``
    - ``speed``

    The generated summaries are intended for prompt construction rather than
    long-term statistical analysis.
    """

    def __init__(self, alerts_data):
        """
    Initialize the alert summarizer.

    Parameters
    ----------
    alerts_data : dict
        Dictionary containing alert information.

        Expected structure::

            {
                "alerts": [
                    {
                        "track_id": int,
                        "class_name": str,
                        "speed": float
                    }
                ]
            }

    Notes
    -----
    After initialization, summaries grouped by object track and object
    class are computed automatically and stored as instance attributes.
    """
        self.alerts = alerts_data.get('alerts', [])
        self.total_alerts = len(self.alerts)
        self.summary_by_track = self._compute_track_summary()
        self.summary_by_class = self._compute_class_summary()

    def _compute_track_summary(self):
        """ Compute a summary of track statistics from the collected alerts.

    This internal method aggregates alert data by track ID, compiling frequency
    counts, speed records, and class name information for each tracked object.
    The summary is used for subsequent analysis and reporting of track behavior
    patterns.

    Returns:
        defaultdict: A dictionary-like object where each key is a track_id (str)
            and each value is a dictionary containing:
            - 'count' (int): Total number of alerts recorded for the track
            - 'speeds' (list[float]): List of speed values associated with the track
            - 'class_name' (str or None): The classification name of the tracked object

    Example:
        Given alerts:
        [
            {'track_id': 'A1', 'speed': 5.2, 'class_name': 'car'},
            {'track_id': 'A1', 'speed': 4.8, 'class_name': 'car'},
            {'track_id': 'B2', 'speed': 3.1, 'class_name': 'pedestrian'}
        ]

        Returns:
        {
            'A1': {'count': 2, 'speeds': [5.2, 4.8], 'class_name': 'car'},
            'B2': {'count': 1, 'speeds': [3.1], 'class_name': 'pedestrian'}
        }

    Note:
        - This method assumes self.alerts is populated with valid alert data
        - Speeds are accumulated in the order alerts were received
        - If multiple class_names exist for the same track_id, the last
          encountered class_name will overwrite previous values
    """
        summary = defaultdict(lambda: {'count': 0, 'speeds': [], 'class_name': None})
        for alert in self.alerts:
            track_id = alert['track_id']
            summary[track_id]['count'] += 1
            summary[track_id]['speeds'].append(alert['speed'])
            summary[track_id]['class_name'] = alert['class_name']
        return summary

    def _compute_class_summary(self):
        """ Compute a summary of track statistics aggregated by object class.

    This internal method processes the per-track summary data to generate
    class-level aggregations, combining statistics for all tracks sharing
    the same classification. The resulting summary provides insights into
    the behavior patterns of different object types across the entire
    tracking system.

    Returns:
        defaultdict: A dictionary-like object where each key is a class_name (str)
            and each value is a dictionary containing:
            - 'count' (int): Total number of alerts across all tracks of this class
            - 'tracks' (set[str]): Set of unique track IDs belonging to this class
            - 'speeds' (list[float]): Aggregated list of all speed values from
              all tracks of this class, in the order they were collected

    Example:
        Given self.summary_by_track:
        {
            'A1': {'count': 2, 'speeds': [5.2, 4.8], 'class_name': 'car'},
            'B2': {'count': 1, 'speeds': [3.1], 'class_name': 'pedestrian'},
            'C3': {'count': 3, 'speeds': [6.0, 5.5, 5.8], 'class_name': 'car'}
        }

        Returns:
        {
            'car': {
                'count': 5,
                'tracks': {'A1', 'C3'},
                'speeds': [5.2, 4.8, 6.0, 5.5, 5.8]
            },
            'pedestrian': {
                'count': 1,
                'tracks': {'B2'},
                'speeds': [3.1]
            }
        }

    Note:
        - This method relies on self.summary_by_track being pre-computed
          (typically via _compute_track_summary)
        - The 'tracks' set preserves uniqueness but does not guarantee order
        - Speeds are extended in the order tracks are iterated from
          summary_by_track, preserving the original sequence within each track
        - Class names are expected to be strings; None values may be included
          if a track lacks classification data
          """

        summary = defaultdict(lambda: {'count': 0, 'tracks': set(), 'speeds': []})
        for track_id, info in self.summary_by_track.items():
            class_name = info['class_name']
            summary[class_name]['count'] += info['count']
            summary[class_name]['tracks'].add(track_id)
            summary[class_name]['speeds'].extend(info['speeds'])
        return summary

    def get_json_summary(self):
        """Generate a JSON-serializable summary of tracking statistics for model consumption.

    This method transforms the internal class-level summary into a compact,
    structured dictionary format optimized for direct transmission to downstream
    models or APIs. It includes high-level statistics and computed metrics such
    as average and maximum speeds per object class.

    Returns:
        dict: A structured summary containing:
            - 'total_alerts' (int): Total number of alerts processed
            - 'alert_classes' (list[str]): List of unique class names detected
            - 'class_statistics' (dict): Nested dictionary mapping each class_name
              to its computed statistics:
                - 'count' (int): Total alert count for this class
                - 'avg_speed' (float): Mean speed rounded to 2 decimal places
                - 'max_speed' (float): Maximum speed rounded to 2 decimal places

    Raises:
        ValueError: If any class in summary_by_class has empty speed lists,
            preventing statistical calculations.

    Example:
        Given self.summary_by_class:
        {
            'car': {'count': 5, 'speeds': [5.2, 4.8, 6.0, 5.5, 5.8]},
            'pedestrian': {'count': 1, 'speeds': [3.1]}
        }

        Returns:
        {
            'total_alerts': 6,
            'alert_classes': ['car', 'pedestrian'],
            'class_statistics': {
                'car': {'count': 5, 'avg_speed': 5.46, 'max_speed': 6.0},
                'pedestrian': {'count': 1, 'avg_speed': 3.1, 'max_speed': 3.1}
            }
        }

    Note:
        - This method is designed for machine learning model integration,
          providing standardized input features
        - Mean and max calculations assume speed lists contain at least one value
        - The function relies on summary_by_class being populated (typically
          via _compute_class_summary)
        - Results are rounded to 2 decimal places for numerical stability
          and compact representation
        - The structure is fully JSON-serializable for API responses
        """
        return {
            "total_alerts": self.total_alerts,
            "alert_classes": list(self.summary_by_class.keys()),
            "class_statistics": {
                class_name: {
                    "count": info['count'],
                    "avg_speed": round(mean(info['speeds']), 2),
                    "max_speed": round(max(info['speeds']), 2)
                }
                for class_name, info in self.summary_by_class.items()
            }
        }

    def get_text_summary(self, max_objects=5, language='fa'):
        """ Generate a human-readable text summary of tracking statistics.

    This method produces a formatted text report containing overall statistics,
    class-level summaries, and the most frequently detected objects. The output
    is designed for display in user interfaces or logs, providing quick insights
    into tracking system performance.

    Args:
        max_objects (int, optional): Maximum number of top tracked objects to
            include in the summary. Defaults to 5. Only the most frequently
            detected tracks (by alert count) are shown.
        language (str, optional): 'fa' for Persian labels (default) or 'en'
            for English labels. Any value other than 'fa' is treated as 'en'.

    Returns:
        str: A multi-line formatted text summary containing:
            - Total alert count
            - List of all detected classes
            - Per-class statistics (incident count and average speed)
            - Top N most active tracks with their details

    Example:
        Given max_objects=2, language='fa' and sample data, returns:

        کل alerts: 6
        طبقات: car, pedestrian

        car: 5 incidents، avg speed 5.5 px/frame
        pedestrian: 1 incidents، avg speed 3.1 px/frame

        The same data with language='en' returns:

        Total alerts: 6
        Classes: car, pedestrian

        car: 5 incidents, avg speed 5.5 px/frame
        pedestrian: 1 incidents, avg speed 3.1 px/frame

    Note:
        - Labels are Persian (Farsi) when language='fa', English otherwise,
          matching the language selection used elsewhere in this class
          (see generate_summary_prompt / generate_detailed_prompt)
        - Speed values are formatted to 1 decimal place for readability
        - Only tracks with at least one alert are considered in top_objects
        - The method relies on summary_by_track and summary_by_class being
          pre-computed (via _compute_track_summary and _compute_class_summary)
        - If max_objects exceeds available tracks, all tracks are included
        - The text format is optimized for console output and simple UI displays
        """
        top_objects = sorted(
            self.summary_by_track.items(),
            key=lambda x: x[1]['count'],
            reverse=True
        )[:max_objects]

        if language == 'fa':
            summary_text = f"کل alerts: {self.total_alerts}\n"
            summary_text += "طبقات: " + ", ".join(self.summary_by_class.keys()) + "\n\n"

            for class_name, info in self.summary_by_class.items():
                summary_text += f"{class_name}: {info['count']} incidents، "
                summary_text += f"avg speed {mean(info['speeds']):.1f} px/frame\n"
        else:
            summary_text = f"Total alerts: {self.total_alerts}\n"
            summary_text += "Classes: " + ", ".join(self.summary_by_class.keys()) + "\n\n"

            for class_name, info in self.summary_by_class.items():
                summary_text += f"{class_name}: {info['count']} incidents, "
                summary_text += f"avg speed {mean(info['speeds']):.1f} px/frame\n"

        return summary_text


class HSEPromptGenerator:
    """ Generate prompts for LLM models using alert summaries.

    This class is responsible for constructing structured prompts that combine
    tracking statistics with contextual instructions for Large Language Models.
    It transforms numerical tracking data into natural language queries that
    enable HSE (Health, Safety, and Environment) analysis and decision support.

    The generator formats summary data from tracking systems into prompt templates
    that guide LLMs to produce safety insights, risk assessments, and operational
    recommendations based on object movement patterns and behavioral analytics.

    Attributes:
        summarizer (AlertsSummarizer): An instance of AlertsSummarizer that
            processes alerts and provides summary statistics. May be None if
            no data has been provided.
        system_prompt (str): Base instruction template defining the LLM's role
            and analytical framework for HSE context.
        user_prompt_template (str): Template string for formatting user queries
            with embedded summary data.

    Note:
        - Designed for Persian language prompts (Farsi) to support local HSE
          operations
        - The class assumes summaries are already computed by the summarizer
        - Prompts are optimized for safety analysis, hazard identification,
          and behavioral pattern recognition
        - Default templates can be overridden via initialization parameters"""

    def __init__(self, alerts_data=None, summarizer=None):
        """
        Args:
            alerts_data: alert data (dict with key 'alerts')
            summarizer: AlertsSummarizer object (optional)
        """
        if summarizer:
            self.summarizer = summarizer
        elif alerts_data:
            self.summarizer = AlertsSummarizer(alerts_data)
        else:
            self.summarizer = None

    def generate_summary_prompt(self, language='fa'):
        """Abbreviated prompt for quick reporting"""

        if not self.summarizer:
            return "❌ No alerts data provided"

        if language == 'fa':
            template_str = """📋 گزارش ایمنی انبار

🔍 خلاصه:
{{ summary_text }}

⚠️ اشیاء خطرناک:
{% for track_id, info in critical_objects %}
  • Track {{ track_id }}: {{ info.class_name }}, {{ info.count }} incidents
{% endfor %}

لطفا گزارش HSE مختصری تولید کن."""
        else:
            template_str = """📋 Warehouse Safety Report

🔍 Summary:
{{ summary_text }}

⚠️ Critical Objects:
{% for track_id, info in critical_objects %}
  • Track {{ track_id }}: {{ info.class_name }}, {{ info.count }} incidents
{% endfor %}

Please generate a concise HSE report."""

        template = Template(template_str)
        critical_objects = sorted(
            self.summarizer.summary_by_track.items(),
            key=lambda x: x[1]['count'],
            reverse=True
        )[:5]

        return template.render(
            summary_text=self.summarizer.get_text_summary(language=language),
            critical_objects=critical_objects
        )

    def generate_detailed_prompt(self, language='fa'):
        """Detailed prompt for full report"""

        if not self.summarizer:
            return "❌ No alerts data provided"

        summary_json = self.summarizer.get_json_summary()

        if language == 'fa':
            template_str = """📋 گزارش تفصیلی ایمنی انبار

⏰ تاریخ: {{ timestamp }}

📊 آمار کلی:
- کل تعداد alerts: {{ total_alerts }}
- طبقات تشخیص‌شده: {{ alert_classes }}

📈 تحلیل هر طبقه:
{% for class_name, stats in class_stats.items() %}
{{ class_name }}:
  - تعداد: {{ stats.count }} incidents
  - سرعت میانگین: {{ stats.avg_speed }} px/frame
  - حداکثر سرعت: {{ stats.max_speed }} px/frame
{% endfor %}

🚨 اشیاء اولویت‌دار:
{% for track_id, info in priority_objects %}
{{ loop.index }}. Track {{ track_id }} ({{ info.class_name }}):
   - تعداد incidents: {{ info.count }}
   - سرعت میانگین: {{ "%.1f"|format(info.avg_speed) }} px/frame
{% endfor %}

لطفا یک گزارش HSE جامع با توصیه‌های ایمنی تولید کن."""
        else:
            template_str = """📋 Detailed Warehouse Safety Report

⏰ Timestamp: {{ timestamp }}

📊 Overall Statistics:
- Total alerts: {{ total_alerts }}
- Detected classes: {{ alert_classes }}

📈 Analysis by Class:
{% for class_name, stats in class_stats.items() %}
{{ class_name }}:
  - Incidents: {{ stats.count }}
  - Avg Speed: {{ stats.avg_speed }} px/frame
  - Max Speed: {{ stats.max_speed }} px/frame
{% endfor %}

🚨 Priority Objects:
{% for track_id, info in priority_objects %}
{{ loop.index }}. Track {{ track_id }} ({{ info.class_name }}):
   - Incident Count: {{ info.count }}
   - Avg Speed: {{ "%.1f"|format(info.avg_speed) }} px/frame
{% endfor %}

Please generate a comprehensive HSE report with safety recommendations."""

        template = Template(template_str)

        priority_objects = sorted(
            self.summarizer.summary_by_track.items(),
            key=lambda x: x[1]['count'],
            reverse=True
        )[:5]

        priority_objects_dict = {
            track_id: {
                'class_name': info['class_name'],
                'count': info['count'],
                'avg_speed': mean(info['speeds']),
                'speeds': info['speeds']
            }
            for track_id, info in priority_objects
        }

        priority_list = [
            (track_id, info)
            for track_id, info in priority_objects_dict.items()
        ]

        return template.render(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            total_alerts=self.summarizer.total_alerts,
            alert_classes=", ".join(self.summarizer.summary_by_class.keys()),
            class_stats=summary_json['class_statistics'],
            priority_objects=priority_list
        )

    def generate_json_prompt(self):

        return json.dumps({

            "role":
                "شما یک متخصص HSE در محیط صنعتی هستید.",

            "alerts":
                self.summarizer.get_json_summary(),

            "rules":
                SAFETY_RULES,

            "task":
                """
                گزارش ایمنی تولید کن.
    
                موارد:
                1- خلاصه وضعیت
                2- تخلفات مهم
                3- سطح ریسک
                4- دلیل خطر
                5- اقدام اصلاحی
    
                فقط بر اساس داده‌ها پاسخ بده.
                علت‌های نامشخص را حدس نزن.
                """,

            "output_format":
                {
                    "summary": "",
                    "risk_level": "",
                    "violations": [
                        {
                            "name": "",
                            "severity": "",
                            "reason": "",
                            "action": ""
                        }
                    ]
                }

        }, indent=2, ensure_ascii=False)
